// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

// API Version of the target Rundeck server.
func GetApiVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "rundeck:apiVersion")
}

// Auth token to use with the Rundeck API.
func GetAuthToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "rundeck:authToken")
}

// URL of the root of the target Rundeck server.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "rundeck:url")
}
