// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck
{
    public partial class RundeckAclPolicy : Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the policy. Must end with `.aclpolicy`.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        [Output("policy")]
        public Output<string> Policy { get; private set; } = null!;


        /// <summary>
        /// Create a RundeckAclPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RundeckAclPolicy(string name, RundeckAclPolicyArgs args, CustomResourceOptions? options = null)
            : base("rundeck:index/rundeckAclPolicy:RundeckAclPolicy", name, args ?? new RundeckAclPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RundeckAclPolicy(string name, Input<string> id, RundeckAclPolicyState? state = null, CustomResourceOptions? options = null)
            : base("rundeck:index/rundeckAclPolicy:RundeckAclPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RundeckAclPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RundeckAclPolicy Get(string name, Input<string> id, RundeckAclPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new RundeckAclPolicy(name, id, state, options);
        }
    }

    public sealed class RundeckAclPolicyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the policy. Must end with `.aclpolicy`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        [Input("policy", required: true)]
        public Input<string> Policy { get; set; } = null!;

        public RundeckAclPolicyArgs()
        {
        }
    }

    public sealed class RundeckAclPolicyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the policy. Must end with `.aclpolicy`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        [Input("policy")]
        public Input<string>? Policy { get; set; }

        public RundeckAclPolicyState()
        {
        }
    }
}
