// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck
{
    /// <summary>
    /// The public key resource allows SSH public keys to be stored into Rundeck's key store.
    /// The key store is where Rundeck keeps credentials that are needed to access the nodes on which
    /// it runs commands.
    /// 
    /// This resource also allows the retrieval of an existing public key from the store, so that it
    /// may be used in the configuration of other resources such as ``aws_key_pair``.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Rundeck = Pulumi.Rundeck;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var anvils = new Rundeck.RundeckPublicKey("anvils", new Rundeck.RundeckPublicKeyArgs
    ///         {
    ///             KeyMaterial = "ssh-rsa yada-yada-yada",
    ///             Path = "anvils/id_rsa.pub",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    public partial class RundeckPublicKey : Pulumi.CustomResource
    {
        /// <summary>
        /// True if the key should be deleted when the resource is deleted. 
        /// Defaults to true if key_material is provided in the configuration.
        /// </summary>
        [Output("delete")]
        public Output<bool> Delete { get; private set; } = null!;

        /// <summary>
        /// The public key string to store, serialized in any way that is accepted
        /// by OpenSSH. If this is not included, ``key_material`` becomes an attribute that can be used
        /// to read the already-existing key material in the Rundeck store.
        /// </summary>
        [Output("keyMaterial")]
        public Output<string> KeyMaterial { get; private set; } = null!;

        /// <summary>
        /// The path within the key store where the key will be stored. By convention
        /// this path name normally ends with ".pub" and otherwise has the same name as the associated
        /// private key.
        /// </summary>
        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        /// <summary>
        /// The URL at which the key material can be retrieved from the key store by other clients.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a RundeckPublicKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RundeckPublicKey(string name, RundeckPublicKeyArgs args, CustomResourceOptions? options = null)
            : base("rundeck:index/rundeckPublicKey:RundeckPublicKey", name, args ?? new RundeckPublicKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RundeckPublicKey(string name, Input<string> id, RundeckPublicKeyState? state = null, CustomResourceOptions? options = null)
            : base("rundeck:index/rundeckPublicKey:RundeckPublicKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RundeckPublicKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RundeckPublicKey Get(string name, Input<string> id, RundeckPublicKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new RundeckPublicKey(name, id, state, options);
        }
    }

    public sealed class RundeckPublicKeyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The public key string to store, serialized in any way that is accepted
        /// by OpenSSH. If this is not included, ``key_material`` becomes an attribute that can be used
        /// to read the already-existing key material in the Rundeck store.
        /// </summary>
        [Input("keyMaterial")]
        public Input<string>? KeyMaterial { get; set; }

        /// <summary>
        /// The path within the key store where the key will be stored. By convention
        /// this path name normally ends with ".pub" and otherwise has the same name as the associated
        /// private key.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public RundeckPublicKeyArgs()
        {
        }
    }

    public sealed class RundeckPublicKeyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// True if the key should be deleted when the resource is deleted. 
        /// Defaults to true if key_material is provided in the configuration.
        /// </summary>
        [Input("delete")]
        public Input<bool>? Delete { get; set; }

        /// <summary>
        /// The public key string to store, serialized in any way that is accepted
        /// by OpenSSH. If this is not included, ``key_material`` becomes an attribute that can be used
        /// to read the already-existing key material in the Rundeck store.
        /// </summary>
        [Input("keyMaterial")]
        public Input<string>? KeyMaterial { get; set; }

        /// <summary>
        /// The path within the key store where the key will be stored. By convention
        /// this path name normally ends with ".pub" and otherwise has the same name as the associated
        /// private key.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// The URL at which the key material can be retrieved from the key store by other clients.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public RundeckPublicKeyState()
        {
        }
    }
}
