// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package rundeck

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type RundeckProject struct {
	pulumi.CustomResourceState

	// The name of a plugin to use to run commands on
	// nodes within this project. Defaults to `jsch-ssh`, which uses the SSH protocol to access the
	// nodes.
	DefaultNodeExecutorPlugin pulumi.StringPtrOutput `pulumi:"defaultNodeExecutorPlugin"`
	// The name of a plugin to use to copy files onto
	// nodes within this project. Defaults to `jsch-scp`, which uses the "Secure Copy" protocol
	// to send files over SSH.
	DefaultNodeFileCopierPlugin pulumi.StringPtrOutput `pulumi:"defaultNodeFileCopierPlugin"`
	// Description of the project to be shown in the Rundeck UI
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Additional raw configuration parameters to include in the project configuration, with dots replaced with slashes in the
	// key names due to limitations in Terraform's config language.
	ExtraConfig pulumi.MapOutput `pulumi:"extraConfig"`
	// The name of the project, used both in the UI and to uniquely identify
	// the project. Must therefore be unique across a single Rundeck installation.
	Name pulumi.StringOutput `pulumi:"name"`
	// Nested block instructing Rundeck on how to determine the
	// set of resources (nodes) for this project. The nested block structure is described below.
	ResourceModelSources RundeckProjectResourceModelSourceArrayOutput `pulumi:"resourceModelSources"`
	// When the SSH-based file copier and executor plugins are
	// used, the type of SSH authentication to use. Defaults to `privateKey`.
	SshAuthenticationType pulumi.StringPtrOutput `pulumi:"sshAuthenticationType"`
	// Like `sshKeyStoragePath` except that the key is read from
	// the Rundeck server's local filesystem, rather than from the key store.
	SshKeyFilePath pulumi.StringPtrOutput `pulumi:"sshKeyFilePath"`
	// When the SSH-based file copier and executor plugins are
	// used, the location within Rundeck's key store where the SSH private key can be found. Private
	// keys can be uploaded to rundeck using the `RundeckPrivateKey` resource.
	SshKeyStoragePath pulumi.StringPtrOutput `pulumi:"sshKeyStoragePath"`
	// The URL of the index page for this project in the Rundeck UI.
	UiUrl pulumi.StringOutput `pulumi:"uiUrl"`
}

// NewRundeckProject registers a new resource with the given unique name, arguments, and options.
func NewRundeckProject(ctx *pulumi.Context,
	name string, args *RundeckProjectArgs, opts ...pulumi.ResourceOption) (*RundeckProject, error) {
	if args == nil || args.ResourceModelSources == nil {
		return nil, errors.New("missing required argument 'ResourceModelSources'")
	}
	if args == nil {
		args = &RundeckProjectArgs{}
	}
	var resource RundeckProject
	err := ctx.RegisterResource("rundeck:index/rundeckProject:RundeckProject", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRundeckProject gets an existing RundeckProject resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRundeckProject(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RundeckProjectState, opts ...pulumi.ResourceOption) (*RundeckProject, error) {
	var resource RundeckProject
	err := ctx.ReadResource("rundeck:index/rundeckProject:RundeckProject", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RundeckProject resources.
type rundeckProjectState struct {
	// The name of a plugin to use to run commands on
	// nodes within this project. Defaults to `jsch-ssh`, which uses the SSH protocol to access the
	// nodes.
	DefaultNodeExecutorPlugin *string `pulumi:"defaultNodeExecutorPlugin"`
	// The name of a plugin to use to copy files onto
	// nodes within this project. Defaults to `jsch-scp`, which uses the "Secure Copy" protocol
	// to send files over SSH.
	DefaultNodeFileCopierPlugin *string `pulumi:"defaultNodeFileCopierPlugin"`
	// Description of the project to be shown in the Rundeck UI
	Description *string `pulumi:"description"`
	// Additional raw configuration parameters to include in the project configuration, with dots replaced with slashes in the
	// key names due to limitations in Terraform's config language.
	ExtraConfig map[string]interface{} `pulumi:"extraConfig"`
	// The name of the project, used both in the UI and to uniquely identify
	// the project. Must therefore be unique across a single Rundeck installation.
	Name *string `pulumi:"name"`
	// Nested block instructing Rundeck on how to determine the
	// set of resources (nodes) for this project. The nested block structure is described below.
	ResourceModelSources []RundeckProjectResourceModelSource `pulumi:"resourceModelSources"`
	// When the SSH-based file copier and executor plugins are
	// used, the type of SSH authentication to use. Defaults to `privateKey`.
	SshAuthenticationType *string `pulumi:"sshAuthenticationType"`
	// Like `sshKeyStoragePath` except that the key is read from
	// the Rundeck server's local filesystem, rather than from the key store.
	SshKeyFilePath *string `pulumi:"sshKeyFilePath"`
	// When the SSH-based file copier and executor plugins are
	// used, the location within Rundeck's key store where the SSH private key can be found. Private
	// keys can be uploaded to rundeck using the `RundeckPrivateKey` resource.
	SshKeyStoragePath *string `pulumi:"sshKeyStoragePath"`
	// The URL of the index page for this project in the Rundeck UI.
	UiUrl *string `pulumi:"uiUrl"`
}

type RundeckProjectState struct {
	// The name of a plugin to use to run commands on
	// nodes within this project. Defaults to `jsch-ssh`, which uses the SSH protocol to access the
	// nodes.
	DefaultNodeExecutorPlugin pulumi.StringPtrInput
	// The name of a plugin to use to copy files onto
	// nodes within this project. Defaults to `jsch-scp`, which uses the "Secure Copy" protocol
	// to send files over SSH.
	DefaultNodeFileCopierPlugin pulumi.StringPtrInput
	// Description of the project to be shown in the Rundeck UI
	Description pulumi.StringPtrInput
	// Additional raw configuration parameters to include in the project configuration, with dots replaced with slashes in the
	// key names due to limitations in Terraform's config language.
	ExtraConfig pulumi.MapInput
	// The name of the project, used both in the UI and to uniquely identify
	// the project. Must therefore be unique across a single Rundeck installation.
	Name pulumi.StringPtrInput
	// Nested block instructing Rundeck on how to determine the
	// set of resources (nodes) for this project. The nested block structure is described below.
	ResourceModelSources RundeckProjectResourceModelSourceArrayInput
	// When the SSH-based file copier and executor plugins are
	// used, the type of SSH authentication to use. Defaults to `privateKey`.
	SshAuthenticationType pulumi.StringPtrInput
	// Like `sshKeyStoragePath` except that the key is read from
	// the Rundeck server's local filesystem, rather than from the key store.
	SshKeyFilePath pulumi.StringPtrInput
	// When the SSH-based file copier and executor plugins are
	// used, the location within Rundeck's key store where the SSH private key can be found. Private
	// keys can be uploaded to rundeck using the `RundeckPrivateKey` resource.
	SshKeyStoragePath pulumi.StringPtrInput
	// The URL of the index page for this project in the Rundeck UI.
	UiUrl pulumi.StringPtrInput
}

func (RundeckProjectState) ElementType() reflect.Type {
	return reflect.TypeOf((*rundeckProjectState)(nil)).Elem()
}

type rundeckProjectArgs struct {
	// The name of a plugin to use to run commands on
	// nodes within this project. Defaults to `jsch-ssh`, which uses the SSH protocol to access the
	// nodes.
	DefaultNodeExecutorPlugin *string `pulumi:"defaultNodeExecutorPlugin"`
	// The name of a plugin to use to copy files onto
	// nodes within this project. Defaults to `jsch-scp`, which uses the "Secure Copy" protocol
	// to send files over SSH.
	DefaultNodeFileCopierPlugin *string `pulumi:"defaultNodeFileCopierPlugin"`
	// Description of the project to be shown in the Rundeck UI
	Description *string `pulumi:"description"`
	// Additional raw configuration parameters to include in the project configuration, with dots replaced with slashes in the
	// key names due to limitations in Terraform's config language.
	ExtraConfig map[string]interface{} `pulumi:"extraConfig"`
	// The name of the project, used both in the UI and to uniquely identify
	// the project. Must therefore be unique across a single Rundeck installation.
	Name *string `pulumi:"name"`
	// Nested block instructing Rundeck on how to determine the
	// set of resources (nodes) for this project. The nested block structure is described below.
	ResourceModelSources []RundeckProjectResourceModelSource `pulumi:"resourceModelSources"`
	// When the SSH-based file copier and executor plugins are
	// used, the type of SSH authentication to use. Defaults to `privateKey`.
	SshAuthenticationType *string `pulumi:"sshAuthenticationType"`
	// Like `sshKeyStoragePath` except that the key is read from
	// the Rundeck server's local filesystem, rather than from the key store.
	SshKeyFilePath *string `pulumi:"sshKeyFilePath"`
	// When the SSH-based file copier and executor plugins are
	// used, the location within Rundeck's key store where the SSH private key can be found. Private
	// keys can be uploaded to rundeck using the `RundeckPrivateKey` resource.
	SshKeyStoragePath *string `pulumi:"sshKeyStoragePath"`
}

// The set of arguments for constructing a RundeckProject resource.
type RundeckProjectArgs struct {
	// The name of a plugin to use to run commands on
	// nodes within this project. Defaults to `jsch-ssh`, which uses the SSH protocol to access the
	// nodes.
	DefaultNodeExecutorPlugin pulumi.StringPtrInput
	// The name of a plugin to use to copy files onto
	// nodes within this project. Defaults to `jsch-scp`, which uses the "Secure Copy" protocol
	// to send files over SSH.
	DefaultNodeFileCopierPlugin pulumi.StringPtrInput
	// Description of the project to be shown in the Rundeck UI
	Description pulumi.StringPtrInput
	// Additional raw configuration parameters to include in the project configuration, with dots replaced with slashes in the
	// key names due to limitations in Terraform's config language.
	ExtraConfig pulumi.MapInput
	// The name of the project, used both in the UI and to uniquely identify
	// the project. Must therefore be unique across a single Rundeck installation.
	Name pulumi.StringPtrInput
	// Nested block instructing Rundeck on how to determine the
	// set of resources (nodes) for this project. The nested block structure is described below.
	ResourceModelSources RundeckProjectResourceModelSourceArrayInput
	// When the SSH-based file copier and executor plugins are
	// used, the type of SSH authentication to use. Defaults to `privateKey`.
	SshAuthenticationType pulumi.StringPtrInput
	// Like `sshKeyStoragePath` except that the key is read from
	// the Rundeck server's local filesystem, rather than from the key store.
	SshKeyFilePath pulumi.StringPtrInput
	// When the SSH-based file copier and executor plugins are
	// used, the location within Rundeck's key store where the SSH private key can be found. Private
	// keys can be uploaded to rundeck using the `RundeckPrivateKey` resource.
	SshKeyStoragePath pulumi.StringPtrInput
}

func (RundeckProjectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*rundeckProjectArgs)(nil)).Elem()
}
