// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("rundeck");

/**
 * API Version of the target Rundeck server.
 */
export let apiVersion: string | undefined = __config.get("apiVersion");
/**
 * Auth token to use with the Rundeck API.
 */
export let authToken: string | undefined = __config.get("authToken");
/**
 * URL of the root of the target Rundeck server.
 */
export let url: string | undefined = __config.get("url");
