// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Outputs
{

    [OutputType]
    public sealed class RundeckJobNotification
    {
        public readonly ImmutableArray<Outputs.RundeckJobNotificationEmail> Emails;
        public readonly ImmutableArray<Outputs.RundeckJobNotificationPlugin> Plugins;
        /// <summary>
        /// The name of the plugin to use.
        /// </summary>
        public readonly string Type;
        public readonly ImmutableArray<string> WebhookUrls;

        [OutputConstructor]
        private RundeckJobNotification(
            ImmutableArray<Outputs.RundeckJobNotificationEmail> emails,

            ImmutableArray<Outputs.RundeckJobNotificationPlugin> plugins,

            string type,

            ImmutableArray<string> webhookUrls)
        {
            Emails = emails;
            Plugins = plugins;
            Type = type;
            WebhookUrls = webhookUrls;
        }
    }
}
