// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Outputs
{

    [OutputType]
    public sealed class RundeckJobCommand
    {
        /// <summary>
        /// A longer description of the job, describing the job in the Rundeck UI.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// gives a whole shell script, inline in the configuration, to execute on the nodes.
        /// </summary>
        public readonly string? InlineScript;
        public readonly ImmutableArray<Outputs.RundeckJobCommandJob> Jobs;
        public readonly ImmutableArray<Outputs.RundeckJobCommandNodeStepPlugin> NodeStepPlugins;
        /// <summary>
        /// and `script_file_args` together describe a script that is already pre-installed
        /// on the nodes which is to be executed.
        /// </summary>
        public readonly string? ScriptFile;
        public readonly string? ScriptFileArgs;
        /// <summary>
        /// gives a single shell command to execute on the nodes.
        /// </summary>
        public readonly string? ShellCommand;
        public readonly ImmutableArray<Outputs.RundeckJobCommandStepPlugin> StepPlugins;

        [OutputConstructor]
        private RundeckJobCommand(
            string? description,

            string? inlineScript,

            ImmutableArray<Outputs.RundeckJobCommandJob> jobs,

            ImmutableArray<Outputs.RundeckJobCommandNodeStepPlugin> nodeStepPlugins,

            string? scriptFile,

            string? scriptFileArgs,

            string? shellCommand,

            ImmutableArray<Outputs.RundeckJobCommandStepPlugin> stepPlugins)
        {
            Description = description;
            InlineScript = inlineScript;
            Jobs = jobs;
            NodeStepPlugins = nodeStepPlugins;
            ScriptFile = scriptFile;
            ScriptFileArgs = scriptFileArgs;
            ShellCommand = shellCommand;
            StepPlugins = stepPlugins;
        }
    }
}
