// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Outputs
{

    [OutputType]
    public sealed class RundeckJobOption
    {
        public readonly bool? AllowMultipleValues;
        public readonly string? DefaultValue;
        /// <summary>
        /// A longer description of the job, describing the job in the Rundeck UI.
        /// </summary>
        public readonly string? Description;
        public readonly bool? ExposedToScripts;
        public readonly string? MultiValueDelimiter;
        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        public readonly string Name;
        public readonly bool? ObscureInput;
        public readonly bool? RequirePredefinedChoice;
        public readonly bool? Required;
        public readonly string? ValidationRegex;
        public readonly ImmutableArray<string> ValueChoices;
        public readonly string? ValueChoicesUrl;

        [OutputConstructor]
        private RundeckJobOption(
            bool? allowMultipleValues,

            string? defaultValue,

            string? description,

            bool? exposedToScripts,

            string? multiValueDelimiter,

            string name,

            bool? obscureInput,

            bool? requirePredefinedChoice,

            bool? required,

            string? validationRegex,

            ImmutableArray<string> valueChoices,

            string? valueChoicesUrl)
        {
            AllowMultipleValues = allowMultipleValues;
            DefaultValue = defaultValue;
            Description = description;
            ExposedToScripts = exposedToScripts;
            MultiValueDelimiter = multiValueDelimiter;
            Name = name;
            ObscureInput = obscureInput;
            RequirePredefinedChoice = requirePredefinedChoice;
            Required = required;
            ValidationRegex = validationRegex;
            ValueChoices = valueChoices;
            ValueChoicesUrl = valueChoicesUrl;
        }
    }
}
