// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Outputs
{

    [OutputType]
    public sealed class RundeckJobCommandJob
    {
        public readonly string? Args;
        /// <summary>
        /// The name of a group within the project in which to place the job.
        /// Setting this creates collapsable subcategories within the Rundeck UI's project job index.
        /// </summary>
        public readonly string? GroupName;
        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        public readonly string Name;
        public readonly Outputs.RundeckJobCommandJobNodefilters? Nodefilters;
        public readonly bool? RunForEachNode;

        [OutputConstructor]
        private RundeckJobCommandJob(
            string? args,

            string? groupName,

            string name,

            Outputs.RundeckJobCommandJobNodefilters? nodefilters,

            bool? runForEachNode)
        {
            Args = args;
            GroupName = groupName;
            Name = name;
            Nodefilters = nodefilters;
            RunForEachNode = runForEachNode;
        }
    }
}
