// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Inputs
{

    public sealed class RundeckJobCommandJobArgs : Pulumi.ResourceArgs
    {
        [Input("args")]
        public Input<string>? Args { get; set; }

        /// <summary>
        /// The name of a group within the project in which to place the job.
        /// Setting this creates collapsable subcategories within the Rundeck UI's project job index.
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("nodefilters")]
        public Input<Inputs.RundeckJobCommandJobNodefiltersArgs>? Nodefilters { get; set; }

        [Input("runForEachNode")]
        public Input<bool>? RunForEachNode { get; set; }

        public RundeckJobCommandJobArgs()
        {
        }
    }
}
