// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Inputs
{

    public sealed class RundeckJobCommandJobNodefiltersArgs : Pulumi.ResourceArgs
    {
        [Input("excludeprecedence")]
        public Input<string>? Excludeprecedence { get; set; }

        [Input("filter")]
        public Input<string>? Filter { get; set; }

        public RundeckJobCommandJobNodefiltersArgs()
        {
        }
    }
}
