// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Inputs
{

    public sealed class RundeckJobNotificationEmailArgs : Pulumi.ResourceArgs
    {
        [Input("attachLog")]
        public Input<bool>? AttachLog { get; set; }

        [Input("recipients", required: true)]
        private InputList<string>? _recipients;
        public InputList<string> Recipients
        {
            get => _recipients ?? (_recipients = new InputList<string>());
            set => _recipients = value;
        }

        [Input("subject")]
        public Input<string>? Subject { get; set; }

        public RundeckJobNotificationEmailArgs()
        {
        }
    }
}
