// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Inputs
{

    public sealed class RundeckJobOptionGetArgs : Pulumi.ResourceArgs
    {
        [Input("allowMultipleValues")]
        public Input<bool>? AllowMultipleValues { get; set; }

        [Input("defaultValue")]
        public Input<string>? DefaultValue { get; set; }

        /// <summary>
        /// A longer description of the job, describing the job in the Rundeck UI.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("exposedToScripts")]
        public Input<bool>? ExposedToScripts { get; set; }

        [Input("multiValueDelimiter")]
        public Input<string>? MultiValueDelimiter { get; set; }

        /// <summary>
        /// The name of the job, used to describe the job in the Rundeck UI.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("obscureInput")]
        public Input<bool>? ObscureInput { get; set; }

        [Input("requirePredefinedChoice")]
        public Input<bool>? RequirePredefinedChoice { get; set; }

        [Input("required")]
        public Input<bool>? Required { get; set; }

        [Input("validationRegex")]
        public Input<string>? ValidationRegex { get; set; }

        [Input("valueChoices")]
        private InputList<string>? _valueChoices;
        public InputList<string> ValueChoices
        {
            get => _valueChoices ?? (_valueChoices = new InputList<string>());
            set => _valueChoices = value;
        }

        [Input("valueChoicesUrl")]
        public Input<string>? ValueChoicesUrl { get; set; }

        public RundeckJobOptionGetArgs()
        {
        }
    }
}
