// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rundeck.Inputs
{

    public sealed class RundeckJobNotificationArgs : Pulumi.ResourceArgs
    {
        [Input("emails")]
        private InputList<Inputs.RundeckJobNotificationEmailArgs>? _emails;
        public InputList<Inputs.RundeckJobNotificationEmailArgs> Emails
        {
            get => _emails ?? (_emails = new InputList<Inputs.RundeckJobNotificationEmailArgs>());
            set => _emails = value;
        }

        [Input("plugins")]
        private InputList<Inputs.RundeckJobNotificationPluginArgs>? _plugins;
        public InputList<Inputs.RundeckJobNotificationPluginArgs> Plugins
        {
            get => _plugins ?? (_plugins = new InputList<Inputs.RundeckJobNotificationPluginArgs>());
            set => _plugins = value;
        }

        /// <summary>
        /// The name of the plugin to use.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("webhookUrls")]
        private InputList<string>? _webhookUrls;
        public InputList<string> WebhookUrls
        {
            get => _webhookUrls ?? (_webhookUrls = new InputList<string>());
            set => _webhookUrls = value;
        }

        public RundeckJobNotificationArgs()
        {
        }
    }
}
