// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RundeckAclPolicy extends pulumi.CustomResource {
    /**
     * Get an existing RundeckAclPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RundeckAclPolicyState, opts?: pulumi.CustomResourceOptions): RundeckAclPolicy {
        return new RundeckAclPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rundeck:index/rundeckAclPolicy:RundeckAclPolicy';

    /**
     * Returns true if the given object is an instance of RundeckAclPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RundeckAclPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RundeckAclPolicy.__pulumiType;
    }

    /**
     * The name of the policy. Must end with `.aclpolicy`.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The name of the job, used to describe the job in the Rundeck UI.
     */
    public readonly policy!: pulumi.Output<string>;

    /**
     * Create a RundeckAclPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RundeckAclPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RundeckAclPolicyArgs | RundeckAclPolicyState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as RundeckAclPolicyState | undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["policy"] = state ? state.policy : undefined;
        } else {
            const args = argsOrState as RundeckAclPolicyArgs | undefined;
            if (!args || args.policy === undefined) {
                throw new Error("Missing required property 'policy'");
            }
            inputs["name"] = args ? args.name : undefined;
            inputs["policy"] = args ? args.policy : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(RundeckAclPolicy.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RundeckAclPolicy resources.
 */
export interface RundeckAclPolicyState {
    /**
     * The name of the policy. Must end with `.aclpolicy`.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * The name of the job, used to describe the job in the Rundeck UI.
     */
    readonly policy?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RundeckAclPolicy resource.
 */
export interface RundeckAclPolicyArgs {
    /**
     * The name of the policy. Must end with `.aclpolicy`.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * The name of the job, used to describe the job in the Rundeck UI.
     */
    readonly policy: pulumi.Input<string>;
}
